version: '3.1'
services:

  tweet_jpa:
    build: .
    container_name: tweet_jpa
    ports:
      - "18080:8080"
      - "18787:8787"
    restart: always
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
      - PGDATA=/data/postgres
    volumes:
      - ~/data/postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

